### ISSUE TITLE
Feature Request: News API

### ISSUE THREAD

**Issue by ToHindahl** [Ingrim4/TachyonizedCloud-Webpanel#1]
Hi,
kann man hinzufügen das man in den Settings wie bei gomme zb. "Neuer Gamemode hinzugefügt" ,...

mfg

Tobi

**Comment by NurIch99** [comment]
Was du meinen?!

**Comment by ToHindahl** [comment]
Das wie bei gomme in der Actionbar in der Lobby steht das ein neuer spielmodus hinzugekommen ist.
und das man das im webinterface einstellen kann

**Comment by Ingrim4** [comment]
Sowas darf die Community einbauen, das wird kein Teil des CloudSystems
